apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lead-score-pdb
  namespace: lead-score
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: lead-score
      component: api
