apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-namespace.yaml
- 01-configmap.yaml
- 03-deployment.yaml
- 04-service.yaml
- 05-ingress.yaml
- 06-hpa.yaml
- 07-pdb.yaml
- 08-worker-deployment.yaml
- 09-lead-registration-worker-deployment.yaml

# Namespace comum
namespace: lead-score

# Labels comuns
labels:
- pairs:
    app: lead-score
    managed-by: kustomize
  includeSelectors: false

# Annotations comuns
commonAnnotations:
  contact: "devops@yourcompany.com"
